Add steps to run `fix-errors.sh` script and handle failures in `checkmarx-one.yml`
* Add step to run `fix-errors.sh` script
* Add step to log error message and exit with non-zero status if `fix-errors.sh` script fails

diff --git a/.github/workflows/checkmarx-one.yml b/.github/workflows/checkmarx-one.yml
--- a/.github/workflows/checkmarx-one.yml
+++ b/.github/workflows/checkmarx-one.yml
@@ -58,3 +58,6 @@ jobs:
         continue-on-error: false
       - name: Fix Errors
         run: ./fix-errors.sh
+      - name: Check fix-errors.sh script status
+        if: failure()
+        run: echo "Error: fix-errors.sh script failed." && exit 1
