Add step to run `fix-errors.sh` script in Codacy workflow
* Add step to run `fix-errors.sh` script
* Add step to log error message and exit with non-zero status if `fix-errors.sh` script fails

diff --git a/.github/workflows/codacy.yml b/.github/workflows/codacy.yml
--- a/.github/workflows/codacy.yml
+++ b/.github/workflows/codacy.yml
@@ -70,3 +70,8 @@ jobs:
       # Fix Errors
       - name: Fix Errors
         run: ./fix-errors.sh
+
+      # Log error message and exit with non-zero status if fix-errors.sh script fails
+      - name: Check fix-errors.sh script status
+        if: failure()
+        run: echo "Error: fix-errors.sh script failed." && exit 1
