Update python-test-coverage-report.yml
Signed-off-by: Bryan <74067792+Bryan-Roe@users.noreply.github.com>

diff --git a/.github/workflows/python-test-coverage-report.yml b/.github/workflows/python-test-coverage-report.yml
--- a/.github/workflows/python-test-coverage-report.yml
+++ b/.github/workflows/python-test-coverage-report.yml
@@ -19,26 +19,39 @@ jobs:
       run:
         working-directory: python
     steps:
+      # Checkout repository
       - name: Checkout repository
-        uses: actions/checkout@v4.0.0
-      
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+
+      # Download coverage report
       - name: Download coverage report
-        uses: actions/download-artifact@v4.0.0
+        uses: actions/download-artifact@v4
         with:
           github-token: ${{ secrets.GH_ACTIONS_PR_WRITE }}
           run-id: ${{ github.event.workflow_run.id }}
           path: ./python
           merge-multiple: true
 
-      - name: Display structure of downloaded files
-        run: ls
+      # Display structure of downloaded files
+      - name: Validate and Display Files
+        run: |
+          echo "Listing downloaded files:"
+          ls -R ./python
+          if [ ! -f ./python/python-coverage.txt ] || [ ! -f ./python/pytest.xml ]; then
+            echo "Required files are missing. Exiting."
+            exit 1
+          fi
 
+      # Read and set PR number
       - name: Read and set PR number
         run: |
           PR_NUMBER=$(cat pr_number)
           echo "PR number: $PR_NUMBER"
           echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
 
+      # Generate Pytest coverage comment
       - name: Pytest coverage comment
         id: coverageComment
         uses: MishaKav/pytest-coverage-comment@main
